version: '3.5'

volumes:
  trustanchors:
  cabundle:

services:

  trust:
    image: indigoiam/egi-trustanchors
    environment:
      - FORCE_TRUST_ANCHORS_UPDATE=1
    volumes:
      - trustanchors:/etc/grid-security/certificates
      - cabundle:/etc/pki

  ts:
    image: indigoiam/robot-framework

    environment:
      - TZ=Europe/Rome
      - REQUESTS_CA_BUNDLE=/etc/pki/tls/cert.pem
      - OIDC_AGENT_SECRET
      - OIDC_AGENT_CMS_SECRET
      - RUN_DEBUG
      - REPORTS_DIR_BASE
      - ROBOT_ARGS

    volumes:
      - cabundle:/etc/pki
      - trustanchors:/etc/grid-security/certificates
      - .:/home/test/test-suite
      - ./assets/vomses:/etc/vomses:ro
      - ./assets/vomsdir:/etc/grid-security/vomsdir:ro
      - ${HOME}/.config/oidc-agent:/home/test/.config/oidc-agent:ro

    entrypoint: /tini -- sleep infinity

    extra_hosts:
      - "storm.example: 192.168.65.2"
